---
#Credentials for connecting
lightSailSecretKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
lightSailKeyID: xxxxxxxxxxxxxxxxxxxx
ansible_ssh_private_key_file: ~/location/toPemFile

# Details about the VPS
# I have chosen eu-west-2, but you can find
region: eu-west-2
zone: eu-west-2a
blueprint: ubuntu_20_04
bundle: nano_1_0

# Subdomain
instance_name: ansible_test_instance
static_ip_name: ansible_test_ip


domain: example.com
subdomain: test.example.com

# Name of the keypair on your laptop that you will use to
# connect to the instance
keyPair: yourKeyPair

email: test@email.com

certbot_package: "python3-certbot-apache"
certbot_plugin: "nginx"