name: remote ssh command
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Update scripts
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: cd rhomis-ansible && git pull https://github.com/l-gorman/rhomis-ansible.git
